### ISSUE TITLE
Support curly brackets in push notification URL's (for iOS 12 Shortcut links)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#191]
I've been writing an automation & script that when I arrive in a certain Home Assistant zone, it'd send me a push notification that when tapped would run an iOS 12 shortcut. Here's the relevant script:

```
  movie_theater_entered_zone:
    alias: "Entered Movie Theater Zone"
    sequence:
      - service: notify.ios_seans_iphone_xs
        data:
          title: "Entered Movie Theater Zone"
          message: "Tap this notification to run the movie theater mode shortcut!"
          data:
            url: "shortcuts://run-shortcut?name={{Movie theater mode}}"
            push:
              badge: 0
            attachment:
              url: ""
              content-type: jpg
              hide-thumbnail: false
```

When tapping on the notification to launch the URL, it instead just opens Home Assistant without the typical "Open URL?" prompt. So it basically fails silently. 

After some testing, I've determined it's because of the {{  }} curly bracket characters in the Shortcuts URL - once I remove them and make the URL simply "shortcuts://" it launches the app. But then you have to scroll through your list of shortcuts to find it, which kind of eliminates the convenience... Hence this bug report/feature request.

Supporting this functionality would fix one of Shortcuts biggest weaknesses (lack of location triggers) and also make Home Assistant iOS notifications way more powerful. In this example my Shortcut was to lower the brightness of the phone and enable Do Not Disturb mode when I arrived at the movie theater (same would be great for Church). That's just one example of many, it would open lots of possibilities.  Thanks.

**Comment by isabellaalstrom** [comment]
Try making it data_template instead of data. Otherwise you can't have templating. Please report back if it works, would be an awesome feature!

**Comment by SeanPM5** [comment]
Good suggestion, but unfortunately data_template didn't work for me - I get errors and it fails to send the notification at all.

However, I've just found a successful workaround thanks to the instructions and shortcut at [this Reddit link](https://www.reddit.com/r/shortcuts/comments/9hpt4q/get_the_shortcutsxcallbackurl_for_a_specific/). There's another more hidden URL scheme without the curly brackets. The working URL, if your shortcut was called "Movie theater mode" for example would be: ```shortcuts://run-shortcut?name=Movie%20theater%20mode```  (basically the name of your Shortcut with spaces replaced by %20 ). I've tested this and it works perfectly. 

But as the poster there notes, this was functionality that was removed by Apple (and is basically leftover remnants hidden in their code). So there's no guarantee it will continue to work in future versions.

**Comment by ZiroNL** [comment]
Are you sure te URL has to be: shortcuts://run-shortcut?name={{Movie theater mode}} ?
When I encode the URL it would be: shortcuts://run-shortcut?name=%7B%7BMovie%20theater%20mode%7D%7D

When I try the encoded URL there's an error (Translated from dutch): The file does not exists., Shortcut '{{Movie theater mode}}' not found.

Without the brackets it works but you have to encode the URL as SeanPM5 suggests.
This is what Apple says about it:
https://support.apple.com/en-en/guide/shortcuts/run-a-shortcut-from-a-url-apd624386f42/ios

**Comment by robbiet480** [comment]
Fixed via e1ad9bc4e0af6084649fc09445d9d5eb67be4bbb which is in 2.0.

You can now define a shortcut payload in a push notification. Upon tapping the notification, the shortcut will be opened. The resulting reply status (success, failure, canceled) along with any data passed back from Shortcuts.app will be sent back to Home Assistant in a event named `ios.shortcut_run`. The payload looks like this:

```json
{
  "input": {
    "text": "soup",
    "input": "text",
    "name": "XCU"
  },
  "name": "XCU",
  "device": {
    "sourceDevicePermanentID": "AB9F02FE-6AC6-47B8-ADEB-5DD87B489156",
    "sourceDeviceName": "Robbie's iPhone XS Max",
    "sourceDeviceID": "robbies_iphone_xs_max_dev"
  },
  "result": "soup",
  "status": "success"
}
```

Here's a piece of a example automation:

```yaml
- service: notify.my_iphone_xs_max
  data:
    message: "Hello I'm a shortcut notification"
    data:
      shortcut:
        name: "XCU"
        input: "text"
        text: "soup"
```
`input` can be any freeform text, a value pointing to another key in the payload or `clipboard` to use whatever text is on the devices clipboard at launch.
