### ISSUE TITLE
Push location update has stopped

### ISSUE THREAD

**Issue by jjpeet** [home-assistant/home-assistant-iOS#194]
Hi @robbiet480 and @blackgold9 I notice that forcing a location update (used to work well) has recently stopped in the last few beta versions. I would have reported sooner but there were a few new phones in my household which I need to ensure weren't causing the issue.

I've been using this automation successfully for those in my household on the beta version of the app (prior to it not working);
```
- alias: Request Location
  trigger:
  action:
    service: notify.NOTIFIER_All
    data:
      message: "request_location_update"
```
Thx
JP

**Comment by los7702** [comment]
Using apple store version 1.50 it is only in background push doesn’t work. When the app is active, the request is working.

**Comment by robbiet480** [comment]
I've just double checked that this is working in 1.5.1 and 2.0 and both appear fine. Are you still experiencing this issue?

**Comment by jjpeet** [comment]
Hi @robbiet480 I am running 1.5.1.
I use an automation below to request location updates via button on the interface.

It doesn’t matter whether the app is in the foreground or not, nothing seems to happen when I run the automation.

Running 1.5.1.

```
- alias: Request Location
  trigger:
  action:
    service: notify.notifier_all
    data:
      message: "request_location_update"

``` 
Thx
JP
