### ISSUE TITLE
Support replacing a delivered push notification

### ISSUE THREAD

**Issue by mnoorenberghe** [home-assistant/home-assistant-iOS#215]
See https://stackoverflow.com/a/39666412 on using the [apns-collapse-id](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) when talking to the APNS server and then using the [identifier](https://developer.apple.com/documentation/usernotifications/unnotificationrequest/1649634-identifier) to replace delivered notifications.

What I'm asking for is similar to the `tag` functionality of html5 notifications.

**Comment by robbiet480** [comment]
Sadly, this requires AWS SNS support, which they still haven't added after 4 years.

Amazon Pinpoint does support all the new features that APNS HTTP/2 has to offer, but is more of a marketing product than a developer product. I don't foresee moving to it anytime soon.

The only other option would be to stop using SNS and write my own push notification sender on Lambda which would get more costly and with a lot more overhead.

**Comment by mnoorenberghe** [comment]
OK, the alternative is doing it all within the app then. It sounds like that's possible.

**Comment by robbiet480** [comment]
That's another option yes. Although i'd probably actually want to switch to another push solution anyways since there would be a lot of other benefits that come with it, and I somehow get the feeling SNS isn't feeling the love from AWS as of late anyway.

**Comment by robbiet480** [comment]
Update: 2.0 is migrating to a new Firebase Cloud Messaging backend because $reasons. This is now supported. Documentation will be updated to reflect post 2.0 launch.

**Comment by robbiet480** [comment]
@mnoorenberghe FCM is now implemented in 2.0 beta. Here's an example payload to use to set APNS headers:

```yaml
- alias: Notify iOS app
    trigger:
      ...
    action:
      service: notify.mobile_app_robbies_iphone
      data:
        message: "Something happened at home!"
        data:
          apns_headers:
            'apns-collapse-id': 'my-cool-collapse-id'
```
