### ISSUE TITLE
ios notify coerce badge value to int

### ISSUE THREAD

**Issue by rbflurry** [home-assistant/home-assistant-iOS#223]
**Home Assistant release with the issue:**

0.86.3

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io
**Component/platform:**

iOS Notify

**Description of problem:**
The iOS notify service has the ability to set the badge/icon on the app icon with a push notification.
This configuration must be done via an integer in the data structure of the message. The following example works.

```
    - service: notify.ios_iphone
      data:
        message: "Set icon to 1"
        data:
          push:
            badge: 1
```
Creates the following service call.

`'call_service', 'data': {'service_data': {'data': {'push': {'badge': 1}}, 'message': 'Set icon to 1'}, 'domain': 'notify', 'service': 'ios_iphone'}}, 'id': 2}`

However when using the following data template the badge "digit" json is passed as a string and is ignored by the iOS app or server.

```
    - service: notify.ios_iphone
      data_template:
        message: "Dynamically set the icon"
        data:
          push:
            badge: '{{states.input_number.alarm_hour.state|int}}'
```
creates the following service call

`'call_service', 'data': {'service_data': {'data': {'push': {'badge': '5'}}, 'message': 'Dynamically set the icon'}, 'domain': 'notify', 'service': 'ios_iphone'}}, 'id': 2}`

I believe the fix would be to coerce the data passed in the badge service call into an integer like how light brightness is translated.

https://github.com/home-assistant/home-assistant/blob/4f988182587b8b82fdaf1495f37a024730505860/homeassistant/components/light/__init__.py#L89

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
    - service: notify.ios_iphone
      data_template:
        message: "Dynamically set the icon"
        data:
          push:
            badge: '{{states.input_number.alarm_hour.state|int}}'
```

**Traceback (if applicable):**
```

```

**Additional information:**
People that have hit this bug.
https://community.home-assistant.io/t/count-persons-at-home-and-show-on-icon-badge/35327

https://community.home-assistant.io/t/badge-number-updated-dynamically/30304
