### ISSUE TITLE
Ability to send silent notifications

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/home-assistant-iOS#241]
**Following up from #92**: requesting the ability to selectively send silent notifications for use with updating the badge in the background.

**Usage**: Pass 'none' (or similar) as a sound:
```
service: 'notify.ios_jamie'
data:
   message: 'delete_alert'
   data:
      push:
           badge: 0
           sound: 'none'
```

**Context**: I have an automation that monitors `persistent_notification` messages and displays this number as a badge. On dismissal of a notification, I would prefer these to be silently updated in the background.

**Comment by robbiet480** [comment]
Will get this in tonight

**Comment by robbiet480** [comment]
Sorry, got sidetracked, it'll be in soon!

**Comment by gregschwartz** [comment]
This was another feature request I was going to add, thanks!

**Comment by robbiet480** [comment]
Implemented in 2.0 beta.

**Comment by robbiet480** [comment]
Thank @DavidFW1960 for making this a breaking change for everyone that actually wanted sound. To have sound now, you need to set `sound: "default"` in the push dictionary.

```yaml
message: A test message with a sound
push:
  sound:
    name: default
```

**Comment by DavidFW1960** [comment]
I am just an innocent bystander

**Comment by robbiet480** [comment]
Behavior has been changed back thanks to #399. Sound is on by default once more since most people want sound. You can disable sound by setting `sound` to `none` in the notification payload.

**Comment by DavidFW1960** [comment]
Yep!

**Comment by calipee** [comment]
Just for some people having the same problem as I did:
Now the correct structure for IOS is described in the [docs](https://companion.home-assistant.io/docs/notifications/notifications-basic/#iosmacos-specific):
```yml
automation:
  - alias: Make some noise
    trigger:
      ...
    action:
      - service: notify.mobile_app_<your_device_id_here>
        data:
          message: "Ding-dong"
          data:
            push:
              sound: none
```
