### ISSUE TITLE
Actionable notifications - no buttons

### ISSUE THREAD

**Issue by optilude** [home-assistant/home-assistant-iOS#251]
- iOS 12.2
- HA iOS app v 1.5.0 - logged in via non-legacy authentication; “update push settings” tapped
- Home Assistant v0.90.2, behind nginx (which terminates SSL)

HA configuration:

```
ios:
    push:
        categories:
          - name: Test
            identifier: 'atest'
            actions:
              - identifier: 'TEST'
                title: 'Testbutton 1'
```

Notification sent with payload:

```
{"message":"a","data":{"push":{"category":"atest"}}}
```

Result: I get a notification that says “a”, but no buttons.

In #226 there is talk of disabling legacy authentication. The iOS app isn’t using this and in any case I can’t fathom why this would help given the notification is pushed, it just doesn’t get any buttons! I tried anyway (which broke the HA configurator app), but it made no difference.

I have also read forum posts suggesting the case of the identifiers matter. I’ve tried a few things, but as per above does not work.

Is there some way I can debug? Observe what is actually sent to Apple/the app?
