### ISSUE TITLE
Location sensor

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#272]
The new device_tracker in iOS2.0b no longer lists all the attributes for location like zip code etc. 

It seems like this might be by design cause Arsaboo said "There was a discussion at some point that device_trackers should only return the location information to clear up the state machine. Any extra attributes were removed."

It would be nice if this info could get added back as `sensor.mobile_app_location` or something. It was useful information. This template sensor I created before shows some of the now missing location attributes.

```
  # This provides the current address in a friendly style, for example "123 Flatbush Ave, Brooklyn, NY 11217"
  - platform: template
    sensors:
      ios_current_address:
        friendly_name: 'Location'
        icon_template: mdi:map-marker-radius
        entity_id: device_tracker.seans_iphone_xs_beta
        value_template: "{{states.device_tracker.seans_iphone_xs_beta.attributes.location.name}}, {{states.device_tracker.seans_iphone_xs_beta.attributes.location.locality}}, {{states.device_tracker.seans_iphone_xs_beta.attributes.location.administrative_area}}, {{states.device_tracker.seans_iphone_xs_beta.attributes.location.postal_code}}"
```
