### ISSUE TITLE
[2.0b51] Actionable notifications imported from HA don't work

### ISSUE THREAD

**Issue by mgiako** [home-assistant/home-assistant-iOS#321]
In b51 the identifiers of actions in actionable notifications are imported uppercase from HA.

But if I don't set uppercase the identifier of the category too, the notification I get don't have the buttons.

I know that here https://www.home-assistant.io/docs/ecosystem/ios/notifications/actions/ there's no mention of an uppercase category identifier but this is the only method that works for me.

If I define the category in app the identifier is automatically set uppercase, and this way it works!

**Comment by mgiako** [comment]
Ok, think I solved this: the actionable notifications category identifier is simply case sensitive. If I set the call like this:
```
      - service: notify.mobile_app_iphone8
        data_template:
          message: 'whatever'
          data:
            push:
              category: update
```
in the app the category needs to be lowercase (and works if imported from HA)

BUT DOES NOT WORK if I set the category identifier manually in the app since it force the input uppercase.

I think the best solution for the app is matching the identifier case in ios: section when importing from HA.
And don't force uppercase when manually setting the category identifier in the app.

I hope I was clear, otherwise I am available for clarification
