### ISSUE TITLE
Thumbnail not showing in notifications

### ISSUE THREAD

**Issue by devinjparsons** [home-assistant/home-assistant-iOS#39]
Using the camera category or a url image attachment, the notification never contains the thumbnail.  I've tried setting the hide thumbnail attribute to true and false and it still doesn't work.  I did find this post (https://stackoverflow.com/a/39356505) but i'm not sure if the current codebase is using Notification Content Extension or  Notification Service Extension.

EDIT:
Looking through the code I see we are implementing both the Notification Service Extension for the notification and then Notification Content Extension for the playback of the live feed.  It does look like here https://github.com/home-assistant/home-assistant-iOS/blob/master/APNSAttachmentService/NotificationService.swift#L109 that you are setting the fileidentifier to the the attachmentURL.lastPathComponent but in documentation[0] for that method it says this doesn't work for urls, so maybe that is the issue.  It also looks like the identifier is not then being used when calling the init function https://github.com/home-assistant/home-assistant-iOS/blob/master/APNSAttachmentService/NotificationService.swift#L147.

I may be way off on all this, haven't developed in swift for iOS, this is just my poking around at the logic.

[0] - https://developer.apple.com/documentation/foundation/nsstring/1416528-lastpathcomponent

**Comment by mnoorenberghe** [comment]
Could you give an example of what you're doing on the home assistant side to send the notification with the image? I have thumbnails with my notifications working fine for months but I think I had to give the `camera_proxy` URL manually:
```yaml
  action:
    service: notify.matthew
    data_template:
      title: '{{ trigger.to_state.name }}'
      message: '{{ trigger.to_state.state }} events on camera'
      data:
        attachment:
          content-type: jpeg
          url: /api/camera_proxy/camera.office?api_password=…
        tag: '{{ trigger.entity_id }}'
        url: https://zm.….com/zm/index.php?view=…
        entity_id: camera.office
```

**Comment by mnoorenberghe** [comment]
I went back to testing
```yaml
…
data:
  push:
    category: camera
  entity_id: camera.office
```
and I noticed that I also didn't get a thumbnail initially. From reading the code, iOS falls back to looking at the URL suffix to determine the content type of the attachment but the camera_proxy URL doesn't have a file-type suffix so it probably fails because of that. Adding the content-type back (without the`url`) fixed the thumbnails again:
```yaml
…
data:
  attachment:
    content-type: jpeg
  push:
    category: camera
  entity_id: camera.office
```

From the hass docs it wasn't clear to me that `content-type` would have an effect for `category: camera` so I will update the docs to include it but also make a PR to default to `jpeg` for cameras since that seems to be what camera_proxy usually returns.
