### ISSUE TITLE
Critical notifications aren't Critical when sent with data_template

### ISSUE THREAD

**Issue by benjgos** [home-assistant/home-assistant-iOS#432]
Home Assistant 0.97.2 (also happened on 0.93.2). iOS app 2.0.0 (62).

I have a script calling another script with a data_template for critical notifications, the notification arrives but ignores the critical and sound parameters.
First script:
(Tried this with both script.turn_on and calling the service: script..  both produce the same result)
```yaml
test_notification:
  alias: "test_notification"
  sequence:
    - service: script.turn_on
      entity_id: script.send_critical_notification_mobile_app_phone_iphone
      data_template:
        variables:
          notification_title: "This is a test title"
          notification_message: "this is a test message"
```

Script being called:
(I've added the attachment and the subtitle to try and track where the issue is)
```yaml
send_critical_notification_mobile_app_phone_iphone:
  alias: "Send Critical Notification to iPhone"
  sequence:
    - service: notify.mobile_app_phone_iphone
      data_template:
        title: "Alert: {{ notification_title }}"
        message: "Alert: {{ notification_message }}"
        data:
          subtitle: "Subtitle"
          attachment:
            url: "https://github.com/home-assistant/home-assistant-assets/blob/master/logo-round-192x192.png?raw=true"
            content-type: png
            hide-thumbnail: false
          push:
            sound:
              name: "US-EN-Morgan-Freeman-Roommate-Is-Arriving.wav"
              critical: 1
              volume: 1
```

Notification arrives with all the info (title, message, subtitle), with the attachment, and with the correct sound. but not as a critical notification and changing the volume to 0, 0.1, or 1 seems to produce the same volume.

Additional tests:
Calling script.send_critical_notification_mobile_app_phone_iphone directly, produces the same result.
```yaml
send_critical_notification_mobile_app_phone_iphone:
  alias: "Send Critical Notification to iPhone"
  sequence:
    - service: notify.mobile_app_phone_iphone
      data_template:
        title: "A: test title"
        message: "A: test message"
        data:
          subtitle: "Subtitle"
          attachment:
            url: "https://github.com/home-assistant/home-assistant-assets/blob/master/logo-round-192x192.png?raw=true"
            content-type: png
            hide-thumbnail: false
          push:
            sound:
              name: "US-EN-Morgan-Freeman-Roommate-Is-Arriving.wav"
              critical: 1
              volume: 1
```
But, if I change data_template to data, and call it directly,  everything works correctly including the critical notification and the volume can be set.

Please let me know if you need any debug info or logs.

Edit:
Fixed formatting
