### ISSUE TITLE
Mistake in docs - replacing-notifications

### ISSUE THREAD

**Issue by h4nc** [home-assistant/home-assistant-iOS#490]
https://companion.home-assistant.io/en/notifications/basic#replacing-notifications

This 
```
message: "Someone might be in the backyard."
  data:
    apns_headers:
     'apns-collapse-id': 'backyard-motion-detected'
```

should be this

```
message: "Someone might be in the backyard."
data:
  apns_headers:
   'apns-collapse-id': 'backyard-motion-detected'
```
