### ISSUE TITLE
iOS/WebKit: Glance Card hold action works intermittently

### ISSUE THREAD

**Issue by garnern2** [home-assistant/home-assistant-iOS#528]
I have 0.103.5 for my Home Assistant install and the latest iOS update on my iPhone XS as well as the latest iOS companion app. I have never been able to get the hold-action on the glance card to work consistently. The tap action always works, but the hold to pull up more info--which is needed for quickly resetting a light that I've changed (rather than using Alexa)--rarely works, and it never works when I need it. Here's my glance card code:

```
type: glance
columns: 4
show_state: false
entities:
  - entity: light.lamp
    hold_action:
      action: more-info
    tap_action:
      action: toggle
  - entity: light.primary
    hold_action:
      action: more-info
    tap_action:
      action: toggle
  - entity: light.tv_backlight
    hold_action:
      action: more-info
    tap_action:
      action: toggle
  - entity: light.barlight
    hold_action:
      action: more-info
    tap_action:
      action: toggle
```

I have taken the following actions:
Created a new glance card from scratch
Created a new glance card on a new view
Deleted the other lights within the glance card and used only one light and one column
Removing the title
Removing the tap action; which causes it to open more info when tapping
Using my wife's iPhone 8
Using my exchange student's iPhone 7

The hold action simply won't work consistently. Is this a known issue? I would think if so, fixing it would be a priority, since hold actions are more intuitive to be used in a touch type interface rather than clicking with a mouse.
