### ISSUE TITLE
iBeacons with major/minor set to 0 seem not to be detected

### ISSUE THREAD

**Issue by cmsimike** [home-assistant/home-assistant-iOS#76]
Hi,

Based on this comment: https://github.com/home-assistant/home-assistant-iOS/issues/43#issuecomment-345136013 I tried to setup iBeacons to augment my device detection using the ios app. Here is my config via customize

```
 zone.home:
  beacon:
   uuid: some-uuid-for-home
   major: 0
   minor: 0
 zone.work:
  beacon:
   uuid: some-uuid-for-work
   major: 1
   minor: 1
```

To debug functionality, i enabled iBeacon enter/exit notifications. So far, I have only received the work enter/exit notifications. Not once has the notifications for zone.home appeared. Note that the home iBeacons do not have major and minor of 0. I have 3 iBeacons at home (fully covering my entire apartment) with a major/minor of 1,2,3. Ideally if major/minor were set to 0, iBeacon enter/exit would be completely based on uuid.
