### ISSUE TITLE
iBeacon crash

### ISSUE THREAD

**Issue by steve28** [home-assistant/home-assistant-iOS#87]
If I have the following in my `customize.yaml` file, I get a crash in the iOS app when I click "save" in the settings. 

```
zone.home:
  track_ios: true
  beacon:
    uuid: 74278bda-b6444520-8f0c720e-af059935
    major: 1
    minor: 1080
```
this is on iOS 11.2.6, 100% repeatable on both iPhone X and iPhone SE.

Changing `track_ios:` to `false` allows the Save to be pressed without the crash, but then I don't get my iOS devices tracked, which defeats the purpose.
